src/__init__.py
import os
from flask import Flask 

import src.routes.init_routes as init_routes
# import routes.init_routes as init_routes

def charger_routes(app: Flask):
    app.register_blueprint(init_routes.init_app_routes)

# from sqlalchemy import create_engine
def init_app() -> Flask:
    app = Flask(__name__, template_folder='templates')
    charger_routes(app)
    return app

src/routes/init_routes.py
from flask import Flask, render_template, request, redirect, url_for, Blueprint  
from src.db import *
# from db import *

init_app_routes = Blueprint('init_routes', __name__)

#   page d'accueil du site permettant de ce connecter
@init_app_routes.route("/")
@init_app_routes.route("/accueil")
def accueil():
    # users = get_users()
    # for user in users: 
    #   print(user)
      # return "Bonjour"
    return render_template('accueil.html')


@init_app_routes.route("/index", methods=['GET', 'POST'])
def index():
      if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        save_user(username, password)
        return redirect(url_for('init_routes.accueil'), msg=msg)
      return render_template('index.html')

#   page d'inscription du site
@init_app_routes.route("/inscription", methods=['GET', 'POST'])
def inscription():
      if request.method == 'POST':
         prenom = request.form.get('prenom')
         nom = request.form.get('nom')
         email = request.form.get('email')
         password = request.form.get('password')
      #    confpassword = request.get.form('password')
      #    if(confpassword == password):
         save_user(email,password,nom,prenom)   
         return redirect(url_for('init_routes.accueil'))
      return render_template('inscription.html')

src/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Formulaire de connexion</title>
  <link rel="stylesheet" href="../static/styles/style.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
</head>
<body>
  <form action="/index" method="post" autocomplete="off"> 
     
    <h1>Se connecter</h1>
    <div class="social-media">
      <p><i class="fab fa-google"></i></p>
      <p><i class="fab fa-facebook-f"></i></p>
      <p><i class="fab fa-twitter"></i></p>
    </div>
    <p class="choose-email">Ou utiliser mon adresse e-mail :</p>
    
    <div class="inputs">
      <input type="email" id="email" placeholder="Email" name="email"/>
      <input type="password" id="password" placeholder="Mot de passe" autocomplete="on" name="password">
    </div>
    
    <p class="inscription">Je n'ai pas de compte. <a class="worddark" href="{{url_for('init_routes.inscription')}}"><span>Je m'en crée un</span></a></p>

    <div align="center">
      <button type="submit">Se connecter</button>
    </div>
     
  </form> 
</body>
</html>

src/templates/inscription.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulaire d'inscription</title>
    <link rel="stylesheet" href="../static/styles/style.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
</head>

<body>
  <form action="/inscription" method="post">
        <div align="center">
           <a href="{{url_for('init_routes.index')}}">Revenir à la page de connexion</a>
        </div>
     
        <h1>Formulaire d'inscription</h1>
        <p class="choose-email">Pour accéder au site, veuillez remplir le formulaire ci dessous : </p>

        <div class="inputs">
          <input type="prenom" name="prenom" id="prenom" placeholder="Votre prénom*">
          <input type="nom" name="nom" id="nom" placeholder="Votre nom*">
          <input type="email" name="email" id="email" placeholder="Email*">
          <input type="password" name="password" id="password" placeholder="Mot de passe*" autocomplete="on">
          <input type="password" name="confpassword" id="confpassword" placeholder="Confirmez votre mot de passe*" autocomplete="on">
        </div>
        <p class="champs">* : champs obligatoire </p>


        <div align="center">
          <button type="submit" id="bouton">Je crée mon compte</button>
        </div>
  </form>
</body>
</html>